import type { BannedIngredient } from "@/types/ingredient";

export const BANNED_INGREDIENTS: BannedIngredient[] = [
  // ---------------------------------------------------------------------------
  // SEED OILS
  // ---------------------------------------------------------------------------
  {
    canonicalName: "Canola Oil",
    category: "seed_oil",
    aliases: ["canola", "canola oil", "low erucic acid rapeseed oil"],
    severity: "high",
    matchPatterns: [/\bcanola\s*oil\b/i, /\bcanola\b/i],
  },
  {
    canonicalName: "Soybean Oil",
    category: "seed_oil",
    aliases: [
      "soybean oil",
      "soy oil",
      "soya oil",
      "soya bean oil",
      "hydrogenated soybean oil",
    ],
    severity: "high",
    matchPatterns: [
      /\bsoy\s*bean\s*oil\b/i,
      /\bsoy\s*oil\b/i,
      /\bsoya\s*(?:bean\s*)?oil\b/i,
    ],
  },
  {
    canonicalName: "Corn Oil",
    category: "seed_oil",
    aliases: ["corn oil", "maize oil"],
    severity: "high",
    matchPatterns: [/\bcorn\s*oil\b/i, /\bmaize\s*oil\b/i],
  },
  {
    canonicalName: "Sunflower Oil",
    category: "seed_oil",
    aliases: [
      "sunflower oil",
      "sunflower seed oil",
      "high oleic sunflower oil",
    ],
    severity: "high",
    matchPatterns: [/\bsunflower\s*(?:seed\s*)?oil\b/i],
  },
  {
    canonicalName: "Safflower Oil",
    category: "seed_oil",
    aliases: ["safflower oil", "safflower seed oil", "high oleic safflower oil"],
    severity: "high",
    matchPatterns: [/\bsafflower\s*(?:seed\s*)?oil\b/i],
  },
  {
    canonicalName: "Cottonseed Oil",
    category: "seed_oil",
    aliases: ["cottonseed oil", "cotton seed oil"],
    severity: "high",
    matchPatterns: [/\bcotton\s*seed\s*oil\b/i],
  },
  {
    canonicalName: "Rapeseed Oil",
    category: "seed_oil",
    aliases: ["rapeseed oil", "rape seed oil", "colza oil"],
    severity: "high",
    matchPatterns: [/\brape\s*seed\s*oil\b/i, /\bcolza\s*oil\b/i],
  },
  {
    canonicalName: "Grapeseed Oil",
    category: "seed_oil",
    aliases: ["grapeseed oil", "grape seed oil"],
    severity: "medium",
    matchPatterns: [/\bgrape\s*seed\s*oil\b/i],
  },
  {
    canonicalName: "Rice Bran Oil",
    category: "seed_oil",
    aliases: ["rice bran oil", "rice oil"],
    severity: "medium",
    matchPatterns: [/\brice\s*bran\s*oil\b/i, /\brice\s*oil\b/i],
  },
  {
    canonicalName: "Peanut Oil",
    category: "seed_oil",
    aliases: ["peanut oil", "groundnut oil", "arachis oil"],
    severity: "medium",
    matchPatterns: [
      /\bpeanut\s*oil\b/i,
      /\bgroundnut\s*oil\b/i,
      /\barachis\s*oil\b/i,
    ],
  },
  {
    canonicalName: "Vegetable Oil",
    category: "seed_oil",
    aliases: [
      "vegetable oil",
      "vegetable fat",
      "mixed vegetable oils",
      "vegetable oils",
    ],
    severity: "high",
    matchPatterns: [
      /\bvegetable\s*oil(?:s)?\b/i,
      /\bvegetable\s*fat(?:s)?\b/i,
      /\bmixed\s*vegetable\s*oil(?:s)?\b/i,
    ],
  },
  {
    canonicalName: "Palm Oil",
    category: "seed_oil",
    aliases: [
      "palm oil",
      "palm fat",
      "palm olein",
      "palm stearin",
      "fractionated palm oil",
    ],
    severity: "high",
    matchPatterns: [
      /\bpalm\s*oil\b/i,
      /\bpalm\s*fat\b/i,
      /\bpalm\s*olein\b/i,
      /\bpalm\s*stearin\b/i,
    ],
  },
  {
    canonicalName: "Palm Kernel Oil",
    category: "seed_oil",
    aliases: ["palm kernel oil", "palm kernel fat"],
    severity: "high",
    matchPatterns: [/\bpalm\s*kernel\s*(?:oil|fat)\b/i],
  },
  {
    canonicalName: "Margarine",
    category: "seed_oil",
    aliases: ["margarine", "margarin"],
    severity: "high",
    matchPatterns: [/\bmargarin[e]?\b/i],
  },
  {
    canonicalName: "Shortening",
    category: "seed_oil",
    aliases: ["shortening", "vegetable shortening"],
    severity: "high",
    matchPatterns: [/\bshortening\b/i],
  },

  // ---------------------------------------------------------------------------
  // ARTIFICIAL SWEETENERS
  // ---------------------------------------------------------------------------
  {
    canonicalName: "Aspartame",
    category: "artificial_sweetener",
    aliases: [
      "aspartame",
      "nutrasweet",
      "equal",
      "amino sweet",
      "canderel",
      "e951",
    ],
    severity: "high",
    matchPatterns: [
      /\baspartame\b/i,
      /\bnustrasweet\b/i,
      /\bnuTrasweet\b/i,
      /\bequal\b/i,
      /\be[\s-]?951\b/i,
    ],
    eNumbers: ["E951"],
  },
  {
    canonicalName: "Sucralose",
    category: "artificial_sweetener",
    aliases: ["sucralose", "splenda", "e955"],
    severity: "high",
    matchPatterns: [/\bsucralose\b/i, /\bsplenda\b/i, /\be[\s-]?955\b/i],
    eNumbers: ["E955"],
  },
  {
    canonicalName: "Saccharin",
    category: "artificial_sweetener",
    aliases: [
      "saccharin",
      "sodium saccharin",
      "calcium saccharin",
      "sweet'n low",
      "e954",
    ],
    severity: "high",
    matchPatterns: [
      /\bsaccharin\b/i,
      /\bsweet'?n\s*low\b/i,
      /\be[\s-]?954\b/i,
    ],
    eNumbers: ["E954"],
  },
  {
    canonicalName: "Acesulfame Potassium",
    category: "artificial_sweetener",
    aliases: [
      "acesulfame potassium",
      "acesulfame k",
      "ace-k",
      "acesulfame",
      "sunett",
      "sweet one",
      "e950",
    ],
    severity: "high",
    matchPatterns: [
      /\bacesulfame\s*(?:potassium|k)\b/i,
      /\bace[\s-]?k\b/i,
      /\be[\s-]?950\b/i,
    ],
    eNumbers: ["E950"],
  },
  {
    canonicalName: "Neotame",
    category: "artificial_sweetener",
    aliases: ["neotame", "newtame", "e961"],
    severity: "high",
    matchPatterns: [/\bneotame\b/i, /\be[\s-]?961\b/i],
    eNumbers: ["E961"],
  },
  {
    canonicalName: "Advantame",
    category: "artificial_sweetener",
    aliases: ["advantame", "e969"],
    severity: "high",
    matchPatterns: [/\badvan?tame\b/i, /\be[\s-]?969\b/i],
    eNumbers: ["E969"],
  },
  {
    canonicalName: "Erythritol",
    category: "artificial_sweetener",
    aliases: ["erythritol", "e968"],
    severity: "low",
    matchPatterns: [/\berythritol\b/i, /\be[\s-]?968\b/i],
    eNumbers: ["E968"],
  },
  {
    canonicalName: "Xylitol",
    category: "artificial_sweetener",
    aliases: ["xylitol", "e967"],
    severity: "low",
    matchPatterns: [/\bxylitol\b/i, /\be[\s-]?967\b/i],
    eNumbers: ["E967"],
  },
  {
    canonicalName: "Sorbitol",
    category: "artificial_sweetener",
    aliases: ["sorbitol", "sorbitol syrup", "e420"],
    severity: "low",
    matchPatterns: [/\bsorbitol\b/i, /\be[\s-]?420\b/i],
    eNumbers: ["E420"],
  },
  {
    canonicalName: "Maltitol",
    category: "artificial_sweetener",
    aliases: ["maltitol", "maltitol syrup", "e965"],
    severity: "low",
    matchPatterns: [/\bmaltitol\b/i, /\be[\s-]?965\b/i],
    eNumbers: ["E965"],
  },

  // ---------------------------------------------------------------------------
  // PRESERVATIVES
  // ---------------------------------------------------------------------------
  {
    canonicalName: "Sodium Benzoate",
    category: "preservative",
    aliases: ["sodium benzoate", "benzoate of soda", "e211"],
    severity: "high",
    matchPatterns: [
      /\bsodium\s*benzoate\b/i,
      /\bbenzoate\s*of\s*soda\b/i,
      /\be[\s-]?211\b/i,
    ],
    eNumbers: ["E211"],
  },
  {
    canonicalName: "Potassium Sorbate",
    category: "preservative",
    aliases: ["potassium sorbate", "e202"],
    severity: "medium",
    matchPatterns: [/\bpotassium\s*sorbate\b/i, /\be[\s-]?202\b/i],
    eNumbers: ["E202"],
  },
  {
    canonicalName: "Sodium Nitrite",
    category: "preservative",
    aliases: ["sodium nitrite", "e250"],
    severity: "high",
    matchPatterns: [/\bsodium\s*nitrite\b/i, /\be[\s-]?250\b/i],
    eNumbers: ["E250"],
  },
  {
    canonicalName: "Sodium Nitrate",
    category: "preservative",
    aliases: ["sodium nitrate", "e251"],
    severity: "high",
    matchPatterns: [/\bsodium\s*nitrate\b/i, /\be[\s-]?251\b/i],
    eNumbers: ["E251"],
  },
  {
    canonicalName: "BHA (Butylated Hydroxyanisole)",
    category: "preservative",
    aliases: [
      "bha",
      "butylated hydroxyanisole",
      "butyl hydroxyanisole",
      "e320",
    ],
    severity: "high",
    matchPatterns: [
      /\bbha\b/i,
      /\bbutylated\s*hydroxyanisole\b/i,
      /\be[\s-]?320\b/i,
    ],
    eNumbers: ["E320"],
  },
  {
    canonicalName: "BHT (Butylated Hydroxytoluene)",
    category: "preservative",
    aliases: [
      "bht",
      "butylated hydroxytoluene",
      "butyl hydroxytoluene",
      "e321",
    ],
    severity: "high",
    matchPatterns: [
      /\bbht\b/i,
      /\bbutylated\s*hydroxytoluene\b/i,
      /\be[\s-]?321\b/i,
    ],
    eNumbers: ["E321"],
  },
  {
    canonicalName: "TBHQ (Tertiary Butylhydroquinone)",
    category: "preservative",
    aliases: [
      "tbhq",
      "tertiary butylhydroquinone",
      "tert-butylhydroquinone",
      "e319",
    ],
    severity: "high",
    matchPatterns: [
      /\btbhq\b/i,
      /\btert(?:iary)?[\s-]?butylhydroquinone\b/i,
      /\be[\s-]?319\b/i,
    ],
    eNumbers: ["E319"],
  },
  {
    canonicalName: "Sodium Metabisulfite",
    category: "preservative",
    aliases: [
      "sodium metabisulfite",
      "sodium metabisulphite",
      "sodium pyrosulfite",
      "e223",
    ],
    severity: "medium",
    matchPatterns: [
      /\bsodium\s*metabisulfi?te\b/i,
      /\bsodium\s*pyrosulfi?te\b/i,
      /\be[\s-]?223\b/i,
    ],
    eNumbers: ["E223"],
  },
  {
    canonicalName: "Potassium Bisulfite",
    category: "preservative",
    aliases: [
      "potassium bisulfite",
      "potassium bisulphite",
      "potassium hydrogen sulfite",
      "e228",
    ],
    severity: "medium",
    matchPatterns: [
      /\bpotassium\s*bisulfi?te\b/i,
      /\bpotassium\s*hydrogen\s*sulfi?te\b/i,
      /\be[\s-]?228\b/i,
    ],
    eNumbers: ["E228"],
  },
  {
    canonicalName: "Calcium Propionate",
    category: "preservative",
    aliases: ["calcium propionate", "e282"],
    severity: "medium",
    matchPatterns: [/\bcalcium\s*propionate\b/i, /\be[\s-]?282\b/i],
    eNumbers: ["E282"],
  },
  {
    canonicalName: "Sodium Propionate",
    category: "preservative",
    aliases: ["sodium propionate", "e281"],
    severity: "medium",
    matchPatterns: [/\bsodium\s*propionate\b/i, /\be[\s-]?281\b/i],
    eNumbers: ["E281"],
  },
  {
    canonicalName: "EDTA",
    category: "preservative",
    aliases: [
      "edta",
      "calcium disodium edta",
      "disodium edta",
      "ethylenediaminetetraacetic acid",
      "e385",
    ],
    severity: "medium",
    matchPatterns: [
      /\bedta\b/i,
      /\bcalcium\s*disodium\s*edta\b/i,
      /\bdisodium\s*edta\b/i,
      /\bethylenediaminetetraacetic\s*acid\b/i,
      /\be[\s-]?385\b/i,
    ],
    eNumbers: ["E385"],
  },
  {
    canonicalName: "Propyl Gallate",
    category: "preservative",
    aliases: ["propyl gallate", "e310"],
    severity: "medium",
    matchPatterns: [/\bpropyl\s*gallate\b/i, /\be[\s-]?310\b/i],
    eNumbers: ["E310"],
  },
  {
    canonicalName: "Sulfur Dioxide",
    category: "preservative",
    aliases: [
      "sulfur dioxide",
      "sulphur dioxide",
      "so2",
      "e220",
    ],
    severity: "medium",
    matchPatterns: [
      /\bsulfu?r\s*dioxide\b/i,
      /\be[\s-]?220\b/i,
    ],
    eNumbers: ["E220"],
  },
  {
    canonicalName: "Sodium Sulfite",
    category: "preservative",
    aliases: ["sodium sulfite", "sodium sulphite", "e221"],
    severity: "medium",
    matchPatterns: [/\bsodium\s*sulfi?te\b/i, /\be[\s-]?221\b/i],
    eNumbers: ["E221"],
  },

  // ---------------------------------------------------------------------------
  // SYNTHETIC DYES
  // ---------------------------------------------------------------------------
  {
    canonicalName: "Red 40 (Allura Red)",
    category: "synthetic_dye",
    aliases: [
      "red 40",
      "allura red",
      "allura red ac",
      "fd&c red no. 40",
      "fd&c red 40",
      "ci 16035",
      "e129",
    ],
    severity: "high",
    matchPatterns: [
      /\bred\s*(?:#|no\.?\s*)?40\b/i,
      /\ballura\s*red\b/i,
      /\bfd&?c\s*red\s*(?:#|no\.?\s*)?40\b/i,
      /\be[\s-]?129\b/i,
      /\bci\s*16035\b/i,
    ],
    eNumbers: ["E129"],
  },
  {
    canonicalName: "Yellow 5 (Tartrazine)",
    category: "synthetic_dye",
    aliases: [
      "yellow 5",
      "tartrazine",
      "fd&c yellow no. 5",
      "fd&c yellow 5",
      "ci 19140",
      "e102",
    ],
    severity: "high",
    matchPatterns: [
      /\byellow\s*(?:#|no\.?\s*)?5\b/i,
      /\btartrazine\b/i,
      /\bfd&?c\s*yellow\s*(?:#|no\.?\s*)?5\b/i,
      /\be[\s-]?102\b/i,
      /\bci\s*19140\b/i,
    ],
    eNumbers: ["E102"],
  },
  {
    canonicalName: "Yellow 6 (Sunset Yellow)",
    category: "synthetic_dye",
    aliases: [
      "yellow 6",
      "sunset yellow",
      "sunset yellow fcf",
      "fd&c yellow no. 6",
      "fd&c yellow 6",
      "ci 15985",
      "e110",
    ],
    severity: "high",
    matchPatterns: [
      /\byellow\s*(?:#|no\.?\s*)?6\b/i,
      /\bsunset\s*yellow\b/i,
      /\bfd&?c\s*yellow\s*(?:#|no\.?\s*)?6\b/i,
      /\be[\s-]?110\b/i,
      /\bci\s*15985\b/i,
    ],
    eNumbers: ["E110"],
  },
  {
    canonicalName: "Blue 1 (Brilliant Blue)",
    category: "synthetic_dye",
    aliases: [
      "blue 1",
      "brilliant blue",
      "brilliant blue fcf",
      "fd&c blue no. 1",
      "fd&c blue 1",
      "ci 42090",
      "e133",
    ],
    severity: "high",
    matchPatterns: [
      /\bblue\s*(?:#|no\.?\s*)?1\b/i,
      /\bbrilliant\s*blue\b/i,
      /\bfd&?c\s*blue\s*(?:#|no\.?\s*)?1\b/i,
      /\be[\s-]?133\b/i,
      /\bci\s*42090\b/i,
    ],
    eNumbers: ["E133"],
  },
  {
    canonicalName: "Blue 2 (Indigo Carmine)",
    category: "synthetic_dye",
    aliases: [
      "blue 2",
      "indigo carmine",
      "indigotine",
      "fd&c blue no. 2",
      "fd&c blue 2",
      "ci 73015",
      "e132",
    ],
    severity: "high",
    matchPatterns: [
      /\bblue\s*(?:#|no\.?\s*)?2\b/i,
      /\bindigo\s*carmine\b/i,
      /\bindigotine\b/i,
      /\bfd&?c\s*blue\s*(?:#|no\.?\s*)?2\b/i,
      /\be[\s-]?132\b/i,
      /\bci\s*73015\b/i,
    ],
    eNumbers: ["E132"],
  },
  {
    canonicalName: "Green 3 (Fast Green)",
    category: "synthetic_dye",
    aliases: [
      "green 3",
      "fast green",
      "fast green fcf",
      "fd&c green no. 3",
      "fd&c green 3",
      "ci 42053",
      "e143",
    ],
    severity: "high",
    matchPatterns: [
      /\bgreen\s*(?:#|no\.?\s*)?3\b/i,
      /\bfast\s*green\b/i,
      /\bfd&?c\s*green\s*(?:#|no\.?\s*)?3\b/i,
      /\be[\s-]?143\b/i,
      /\bci\s*42053\b/i,
    ],
    eNumbers: ["E143"],
  },
  {
    canonicalName: "Red 3 (Erythrosine)",
    category: "synthetic_dye",
    aliases: [
      "red 3",
      "erythrosine",
      "fd&c red no. 3",
      "fd&c red 3",
      "ci 45430",
      "e127",
    ],
    severity: "high",
    matchPatterns: [
      /\bred\s*(?:#|no\.?\s*)?3\b/i,
      /\berythrosine\b/i,
      /\bfd&?c\s*red\s*(?:#|no\.?\s*)?3\b/i,
      /\be[\s-]?127\b/i,
      /\bci\s*45430\b/i,
    ],
    eNumbers: ["E127"],
  },
  {
    canonicalName: "Citrus Red 2",
    category: "synthetic_dye",
    aliases: ["citrus red 2", "citrus red no. 2", "ci 12156"],
    severity: "high",
    matchPatterns: [
      /\bcitrus\s*red\s*(?:#|no\.?\s*)?2\b/i,
      /\bci\s*12156\b/i,
    ],
  },
  {
    canonicalName: "Caramel Color",
    category: "synthetic_dye",
    aliases: [
      "caramel color",
      "caramel colour",
      "caramel coloring",
      "caramel colouring",
      "class iv caramel color",
      "ammonia sulfite caramel",
      "e150d",
      "e150a",
      "e150b",
      "e150c",
    ],
    severity: "medium",
    matchPatterns: [
      /\bcaramel\s*colou?r(?:ing)?\b/i,
      /\be[\s-]?150[a-d]?\b/i,
      /\bammonia\s*sulfi?te\s*caramel\b/i,
    ],
    eNumbers: ["E150a", "E150b", "E150c", "E150d"],
  },
  {
    canonicalName: "Titanium Dioxide",
    category: "synthetic_dye",
    aliases: ["titanium dioxide", "tio2", "e171", "ci 77891"],
    severity: "high",
    matchPatterns: [
      /\btitanium\s*dioxide\b/i,
      /\btio2\b/i,
      /\be[\s-]?171\b/i,
      /\bci\s*77891\b/i,
    ],
    eNumbers: ["E171"],
  },
  {
    canonicalName: "FD&C Colors (Generic)",
    category: "synthetic_dye",
    aliases: [
      "fd&c color",
      "fd&c colours",
      "fd&c dye",
      "certified color",
      "artificial color",
      "artificial colour",
      "artificial coloring",
      "synthetic color",
    ],
    severity: "high",
    matchPatterns: [
      /\bfd&?c\s*(?:colou?r|dye)/i,
      /\bartificial\s*colou?r(?:ing|s)?\b/i,
      /\bcertified\s*colou?r(?:s)?\b/i,
      /\bsynthetic\s*colou?r(?:s)?\b/i,
    ],
  },
  {
    canonicalName: "Red 40 Lake",
    category: "synthetic_dye",
    aliases: ["red 40 lake", "allura red lake", "fd&c red 40 aluminum lake"],
    severity: "high",
    matchPatterns: [
      /\bred\s*40\s*lake\b/i,
      /\ballura\s*red\s*lake\b/i,
    ],
    eNumbers: ["E129"],
  },
  {
    canonicalName: "Yellow 5 Lake",
    category: "synthetic_dye",
    aliases: ["yellow 5 lake", "tartrazine lake", "fd&c yellow 5 aluminum lake"],
    severity: "high",
    matchPatterns: [
      /\byellow\s*5\s*lake\b/i,
      /\btartrazine\s*lake\b/i,
    ],
    eNumbers: ["E102"],
  },
  {
    canonicalName: "Yellow 6 Lake",
    category: "synthetic_dye",
    aliases: ["yellow 6 lake", "sunset yellow lake"],
    severity: "high",
    matchPatterns: [
      /\byellow\s*6\s*lake\b/i,
      /\bsunset\s*yellow\s*lake\b/i,
    ],
    eNumbers: ["E110"],
  },
  {
    canonicalName: "Blue 1 Lake",
    category: "synthetic_dye",
    aliases: ["blue 1 lake", "brilliant blue lake"],
    severity: "high",
    matchPatterns: [
      /\bblue\s*1\s*lake\b/i,
      /\bbrilliant\s*blue\s*lake\b/i,
    ],
    eNumbers: ["E133"],
  },

  // ---------------------------------------------------------------------------
  // EMULSIFIERS
  // ---------------------------------------------------------------------------
  {
    canonicalName: "Polysorbate 80",
    category: "emulsifier",
    aliases: ["polysorbate 80", "tween 80", "polyoxyethylene sorbitan monooleate", "e433"],
    severity: "high",
    matchPatterns: [
      /\bpolysorbate\s*80\b/i,
      /\btween\s*80\b/i,
      /\be[\s-]?433\b/i,
    ],
    eNumbers: ["E433"],
  },
  {
    canonicalName: "Polysorbate 60",
    category: "emulsifier",
    aliases: ["polysorbate 60", "tween 60", "polyoxyethylene sorbitan monostearate", "e435"],
    severity: "high",
    matchPatterns: [
      /\bpolysorbate\s*60\b/i,
      /\btween\s*60\b/i,
      /\be[\s-]?435\b/i,
    ],
    eNumbers: ["E435"],
  },
  {
    canonicalName: "Carrageenan",
    category: "emulsifier",
    aliases: [
      "carrageenan",
      "carrageenin",
      "irish moss extract",
      "chondrus extract",
      "e407",
      "e407a",
    ],
    severity: "high",
    matchPatterns: [
      /\bcarrageenan\b/i,
      /\bcarrageenin\b/i,
      /\birish\s*moss\s*extract\b/i,
      /\bchondrus\s*extract\b/i,
      /\be[\s-]?407a?\b/i,
    ],
    eNumbers: ["E407", "E407a"],
  },
  {
    canonicalName: "Sodium Stearoyl Lactylate",
    category: "emulsifier",
    aliases: ["sodium stearoyl lactylate", "ssl", "sodium stearoyl-2-lactylate", "e481"],
    severity: "medium",
    matchPatterns: [
      /\bsodium\s*stearoyl\s*(?:2-)?lactylate\b/i,
      /\be[\s-]?481\b/i,
    ],
    eNumbers: ["E481"],
  },
  {
    canonicalName: "DATEM",
    category: "emulsifier",
    aliases: [
      "datem",
      "diacetyl tartaric acid esters of mono- and diglycerides",
      "diacetyl tartaric acid ester",
      "e472e",
    ],
    severity: "medium",
    matchPatterns: [
      /\bdatem\b/i,
      /\bdiacetyl\s*tartaric\s*acid\s*ester/i,
      /\be[\s-]?472e\b/i,
    ],
    eNumbers: ["E472e"],
  },
  {
    canonicalName: "Mono- and Diglycerides",
    category: "emulsifier",
    aliases: [
      "mono- and diglycerides",
      "mono and diglycerides",
      "monoglycerides",
      "diglycerides",
      "mono-diglycerides",
      "e471",
    ],
    severity: "medium",
    matchPatterns: [
      /\bmono[\s-]?(?:and\s*)?di\s*glycerides\b/i,
      /\bmonoglycerides\b/i,
      /\bdiglycerides\b/i,
      /\be[\s-]?471\b/i,
    ],
    eNumbers: ["E471"],
  },
  {
    canonicalName: "Carboxymethylcellulose (Cellulose Gum)",
    category: "emulsifier",
    aliases: [
      "carboxymethylcellulose",
      "cellulose gum",
      "cmc",
      "sodium carboxymethylcellulose",
      "e466",
    ],
    severity: "medium",
    matchPatterns: [
      /\bcarboxymethyl\s*cellulose\b/i,
      /\bcellulose\s*gum\b/i,
      /\bsodium\s*carboxymethyl\s*cellulose\b/i,
      /\be[\s-]?466\b/i,
    ],
    eNumbers: ["E466"],
  },
  {
    canonicalName: "Xanthan Gum",
    category: "emulsifier",
    aliases: ["xanthan gum", "xanthan", "e415"],
    severity: "low",
    matchPatterns: [/\bxanthan\s*(?:gum)?\b/i, /\be[\s-]?415\b/i],
    eNumbers: ["E415"],
  },
  {
    canonicalName: "Soy Lecithin",
    category: "emulsifier",
    aliases: ["soy lecithin", "soya lecithin", "lecithin (soy)", "e322"],
    severity: "low",
    matchPatterns: [
      /\bsoy(?:a)?\s*lecithin\b/i,
      /\blecithin\s*\(soy\)/i,
      /\be[\s-]?322\b/i,
    ],
    eNumbers: ["E322"],
  },
  {
    canonicalName: "Propylene Glycol Alginate",
    category: "emulsifier",
    aliases: ["propylene glycol alginate", "pga", "e405"],
    severity: "medium",
    matchPatterns: [
      /\bpropylene\s*glycol\s*alginate\b/i,
      /\be[\s-]?405\b/i,
    ],
    eNumbers: ["E405"],
  },

  // ---------------------------------------------------------------------------
  // FLAVOR ENHANCERS
  // ---------------------------------------------------------------------------
  {
    canonicalName: "Monosodium Glutamate (MSG)",
    category: "flavor_enhancer",
    aliases: [
      "monosodium glutamate",
      "msg",
      "sodium glutamate",
      "glutamic acid",
      "e621",
    ],
    severity: "high",
    matchPatterns: [
      /\bmonosodium\s*glutamate\b/i,
      /\bmsg\b/i,
      /\bsodium\s*glutamate\b/i,
      /\be[\s-]?621\b/i,
    ],
    eNumbers: ["E621"],
  },
  {
    canonicalName: "Disodium Guanylate",
    category: "flavor_enhancer",
    aliases: ["disodium guanylate", "sodium guanylate", "e627"],
    severity: "medium",
    matchPatterns: [
      /\bdisodium\s*guanylate\b/i,
      /\bsodium\s*guanylate\b/i,
      /\be[\s-]?627\b/i,
    ],
    eNumbers: ["E627"],
  },
  {
    canonicalName: "Disodium Inosinate",
    category: "flavor_enhancer",
    aliases: ["disodium inosinate", "sodium inosinate", "e631"],
    severity: "medium",
    matchPatterns: [
      /\bdisodium\s*inosinate\b/i,
      /\bsodium\s*inosinate\b/i,
      /\be[\s-]?631\b/i,
    ],
    eNumbers: ["E631"],
  },
  {
    canonicalName: "Autolyzed Yeast Extract",
    category: "flavor_enhancer",
    aliases: [
      "autolyzed yeast extract",
      "autolyzed yeast",
      "yeast extract",
      "autolysed yeast extract",
    ],
    severity: "medium",
    matchPatterns: [
      /\bautoly[sz]ed\s*yeast\s*(?:extract)?\b/i,
      /\byeast\s*extract\b/i,
    ],
  },
  {
    canonicalName: "Hydrolyzed Protein",
    category: "flavor_enhancer",
    aliases: [
      "hydrolyzed protein",
      "hydrolyzed vegetable protein",
      "hydrolyzed soy protein",
      "hydrolyzed plant protein",
      "hvp",
      "hydrolysed protein",
    ],
    severity: "medium",
    matchPatterns: [
      /\bhydroly[sz]ed\s*(?:vegetable\s*|soy\s*|plant\s*|corn\s*|wheat\s*)?protein\b/i,
      /\bhvp\b/i,
    ],
  },
  {
    canonicalName: "Maltodextrin",
    category: "flavor_enhancer",
    aliases: ["maltodextrin", "corn maltodextrin", "wheat maltodextrin"],
    severity: "medium",
    matchPatterns: [/\bmaltodextrin\b/i],
  },
  {
    canonicalName: "Natural Flavors (Generic)",
    category: "flavor_enhancer",
    aliases: [
      "natural flavors",
      "natural flavours",
      "natural flavor",
      "natural flavour",
      "natural flavoring",
      "natural flavouring",
    ],
    severity: "low",
    matchPatterns: [/\bnatural\s*flavou?r(?:s|ing|ings)?\b/i],
  },
  {
    canonicalName: "Artificial Flavors",
    category: "flavor_enhancer",
    aliases: [
      "artificial flavors",
      "artificial flavours",
      "artificial flavor",
      "artificial flavour",
      "artificial flavoring",
      "artificial flavouring",
    ],
    severity: "high",
    matchPatterns: [/\bartificial\s*flavou?r(?:s|ing|ings)?\b/i],
  },
  {
    canonicalName: "Diacetyl",
    category: "flavor_enhancer",
    aliases: ["diacetyl", "2,3-butanedione"],
    severity: "high",
    matchPatterns: [/\bdiacetyl\b/i, /\b2,3[\s-]?butanedione\b/i],
  },
  {
    canonicalName: "Torula Yeast",
    category: "flavor_enhancer",
    aliases: ["torula yeast", "torula", "candida utilis"],
    severity: "low",
    matchPatterns: [/\btorula\s*(?:yeast)?\b/i, /\bcandida\s*utilis\b/i],
  },

  // ---------------------------------------------------------------------------
  // TRANS FATS
  // ---------------------------------------------------------------------------
  {
    canonicalName: "Partially Hydrogenated Oil",
    category: "trans_fat",
    aliases: [
      "partially hydrogenated oil",
      "partially hydrogenated soybean oil",
      "partially hydrogenated cottonseed oil",
      "partially hydrogenated palm oil",
      "partially hydrogenated coconut oil",
      "partially hydrogenated vegetable oil",
      "partially hydrogenated canola oil",
    ],
    severity: "high",
    matchPatterns: [/\bpartially\s*hydrogenated\s*\w+\s*oil\b/i],
  },
  {
    canonicalName: "Hydrogenated Oil",
    category: "trans_fat",
    aliases: [
      "hydrogenated oil",
      "fully hydrogenated oil",
      "hydrogenated vegetable oil",
      "hydrogenated soybean oil",
      "hydrogenated palm oil",
      "hydrogenated cottonseed oil",
      "hydrogenated coconut oil",
    ],
    severity: "high",
    matchPatterns: [
      /\b(?:fully\s*)?hydrogenated\s*\w+\s*oil\b/i,
      /\bhydrogenated\s*(?:vegetable\s*)?oil\b/i,
    ],
  },
  {
    canonicalName: "Interesterified Fat",
    category: "trans_fat",
    aliases: [
      "interesterified fat",
      "interesterified oil",
      "interesterified vegetable fat",
    ],
    severity: "high",
    matchPatterns: [/\binteresterified\s*(?:fat|oil|vegetable\s*fat)\b/i],
  },
  {
    canonicalName: "Mono- and Diglycerides of Fatty Acids",
    category: "trans_fat",
    aliases: [
      "mono- and diglycerides of fatty acids",
      "mono and diglycerides of fatty acids",
      "glycerol esters of fatty acids",
    ],
    severity: "medium",
    matchPatterns: [
      /\bmono[\s-]?(?:and\s*)?di\s*glycerides\s*of\s*fatty\s*acids\b/i,
      /\bglycerol\s*esters?\s*of\s*fatty\s*acids\b/i,
    ],
  },
  {
    canonicalName: "Shortening (Trans Fat Source)",
    category: "trans_fat",
    aliases: [
      "vegetable shortening",
      "hydrogenated shortening",
      "partially hydrogenated shortening",
    ],
    severity: "high",
    matchPatterns: [
      /\b(?:vegetable|hydrogenated|partially\s*hydrogenated)\s*shortening\b/i,
    ],
  },

  // ---------------------------------------------------------------------------
  // PROCESSING AGENTS
  // ---------------------------------------------------------------------------
  {
    canonicalName: "High Fructose Corn Syrup",
    category: "processing_agent",
    aliases: [
      "high fructose corn syrup",
      "hfcs",
      "high-fructose corn syrup",
      "hfcs-55",
      "hfcs-42",
      "hfcs-90",
      "glucose-fructose syrup",
      "isoglucose",
    ],
    severity: "high",
    matchPatterns: [
      /\bhigh[\s-]?fructose\s*corn\s*syrup\b/i,
      /\bhfcs(?:[\s-]?\d+)?\b/i,
      /\bglucose[\s-]?fructose\s*syrup\b/i,
      /\bisoglucose\b/i,
    ],
  },
  {
    canonicalName: "Corn Syrup Solids",
    category: "processing_agent",
    aliases: ["corn syrup solids", "dried corn syrup", "corn syrup powder"],
    severity: "medium",
    matchPatterns: [
      /\bcorn\s*syrup\s*solids\b/i,
      /\bdried\s*corn\s*syrup\b/i,
    ],
  },
  {
    canonicalName: "Modified Food Starch",
    category: "processing_agent",
    aliases: [
      "modified food starch",
      "modified corn starch",
      "modified starch",
      "modified tapioca starch",
      "modified potato starch",
    ],
    severity: "medium",
    matchPatterns: [
      /\bmodified\s*(?:food\s*|corn\s*|tapioca\s*|potato\s*)?starch\b/i,
    ],
  },
  {
    canonicalName: "Bleached Flour",
    category: "processing_agent",
    aliases: [
      "bleached flour",
      "bleached wheat flour",
      "bleached enriched flour",
      "bleached all-purpose flour",
    ],
    severity: "medium",
    matchPatterns: [/\bbleached\s*(?:\w+\s*)*flour\b/i],
  },
  {
    canonicalName: "Potassium Bromate (Bromated Flour)",
    category: "processing_agent",
    aliases: [
      "potassium bromate",
      "bromated flour",
      "bromate",
      "e924",
    ],
    severity: "high",
    matchPatterns: [
      /\bpotassium\s*bromate\b/i,
      /\bbromated\s*flour\b/i,
      /\bbromate\b/i,
      /\be[\s-]?924\b/i,
    ],
    eNumbers: ["E924"],
  },
  {
    canonicalName: "Azodicarbonamide",
    category: "processing_agent",
    aliases: [
      "azodicarbonamide",
      "ada",
      "azo(bis)formamide",
      "e927a",
    ],
    severity: "high",
    matchPatterns: [
      /\bazodicarbonamide\b/i,
      /\bazo\s*\(?\s*bis\s*\)?\s*formamide\b/i,
      /\be[\s-]?927a\b/i,
    ],
    eNumbers: ["E927a"],
  },
  {
    canonicalName: "Silicon Dioxide",
    category: "processing_agent",
    aliases: [
      "silicon dioxide",
      "silica",
      "sio2",
      "e551",
    ],
    severity: "low",
    matchPatterns: [
      /\bsilicon\s*dioxide\b/i,
      /\bsilica\b/i,
      /\be[\s-]?551\b/i,
    ],
    eNumbers: ["E551"],
  },
  {
    canonicalName: "Calcium Peroxide",
    category: "processing_agent",
    aliases: ["calcium peroxide", "e930"],
    severity: "medium",
    matchPatterns: [/\bcalcium\s*peroxide\b/i, /\be[\s-]?930\b/i],
    eNumbers: ["E930"],
  },
  {
    canonicalName: "Sodium Aluminum Phosphate",
    category: "processing_agent",
    aliases: [
      "sodium aluminum phosphate",
      "sodium aluminium phosphate",
      "salp",
      "e541",
    ],
    severity: "medium",
    matchPatterns: [
      /\bsodium\s*alumini?um\s*phosphate\b/i,
      /\be[\s-]?541\b/i,
    ],
    eNumbers: ["E541"],
  },
  {
    canonicalName: "Sodium Aluminum Sulfate",
    category: "processing_agent",
    aliases: [
      "sodium aluminum sulfate",
      "sodium aluminium sulphate",
      "sas",
    ],
    severity: "medium",
    matchPatterns: [/\bsodium\s*alumini?um\s*sulfu?ate\b/i],
  },

  // ---------------------------------------------------------------------------
  // OTHER
  // ---------------------------------------------------------------------------
  {
    canonicalName: "Dimethylpolysiloxane",
    category: "other",
    aliases: [
      "dimethylpolysiloxane",
      "pdms",
      "polydimethylsiloxane",
      "dimethicone",
      "e900",
    ],
    severity: "medium",
    matchPatterns: [
      /\bdimethylpolysiloxane\b/i,
      /\bpolydimethylsiloxane\b/i,
      /\bdimethicone\b/i,
      /\bpdms\b/i,
      /\be[\s-]?900\b/i,
    ],
    eNumbers: ["E900"],
  },
  {
    canonicalName: "PGPR (Polyglycerol Polyricinoleate)",
    category: "other",
    aliases: [
      "pgpr",
      "polyglycerol polyricinoleate",
      "e476",
    ],
    severity: "medium",
    matchPatterns: [
      /\bpgpr\b/i,
      /\bpolyglycerol\s*polyricinoleate\b/i,
      /\be[\s-]?476\b/i,
    ],
    eNumbers: ["E476"],
  },
  {
    canonicalName: "Hexane-Extracted Ingredients",
    category: "other",
    aliases: [
      "hexane extracted",
      "hexane-extracted",
      "hexane processed",
    ],
    severity: "high",
    matchPatterns: [/\bhexane[\s-]?extracted\b/i, /\bhexane[\s-]?processed\b/i],
  },
  {
    canonicalName: "Sodium Caseinate",
    category: "other",
    aliases: ["sodium caseinate", "caseinates"],
    severity: "low",
    matchPatterns: [/\bsodium\s*caseinate\b/i, /\bcaseinates?\b/i],
  },
  {
    canonicalName: "Carnauba Wax",
    category: "other",
    aliases: ["carnauba wax", "brazil wax", "e903"],
    severity: "low",
    matchPatterns: [
      /\bcarnauba\s*wax\b/i,
      /\bbrazil\s*wax\b/i,
      /\be[\s-]?903\b/i,
    ],
    eNumbers: ["E903"],
  },
  {
    canonicalName: "Shellac",
    category: "other",
    aliases: ["shellac", "confectioner's glaze", "pharmaceutical glaze", "e904"],
    severity: "low",
    matchPatterns: [
      /\bshellac\b/i,
      /\bconfectioner'?s?\s*glaze\b/i,
      /\bpharmaceutical\s*glaze\b/i,
      /\be[\s-]?904\b/i,
    ],
    eNumbers: ["E904"],
  },
  {
    canonicalName: "Magnesium Stearate",
    category: "other",
    aliases: ["magnesium stearate", "e470b"],
    severity: "low",
    matchPatterns: [
      /\bmagnesium\s*stearate\b/i,
      /\be[\s-]?470b\b/i,
    ],
    eNumbers: ["E470b"],
  },
  {
    canonicalName: "Propylene Glycol",
    category: "other",
    aliases: ["propylene glycol", "1,2-propanediol", "e1520"],
    severity: "medium",
    matchPatterns: [
      /\bpropylene\s*glycol\b/i,
      /\b1,2[\s-]?propanediol\b/i,
      /\be[\s-]?1520\b/i,
    ],
    eNumbers: ["E1520"],
  },
  {
    canonicalName: "Butane / Isobutane (Propellants)",
    category: "other",
    aliases: [
      "butane",
      "isobutane",
      "propellant",
      "e943a",
      "e943b",
    ],
    severity: "high",
    matchPatterns: [
      /\bbutane\b/i,
      /\bisobutane\b/i,
      /\be[\s-]?943[ab]?\b/i,
    ],
    eNumbers: ["E943a", "E943b"],
  },
  {
    canonicalName: "Microcrystalline Cellulose",
    category: "other",
    aliases: ["microcrystalline cellulose", "mcc", "cellulose powder", "e460"],
    severity: "low",
    matchPatterns: [
      /\bmicrocrystalline\s*cellulose\b/i,
      /\bcellulose\s*powder\b/i,
      /\be[\s-]?460\b/i,
    ],
    eNumbers: ["E460"],
  },
  {
    canonicalName: "Sodium Tripolyphosphate",
    category: "other",
    aliases: [
      "sodium tripolyphosphate",
      "stpp",
      "e451",
    ],
    severity: "medium",
    matchPatterns: [
      /\bsodium\s*tripolyphosphate\b/i,
      /\bstpp\b/i,
      /\be[\s-]?451\b/i,
    ],
    eNumbers: ["E451"],
  },
  {
    canonicalName: "Calcium Sulfate",
    category: "other",
    aliases: ["calcium sulfate", "calcium sulphate", "gypsum", "e516"],
    severity: "low",
    matchPatterns: [
      /\bcalcium\s*sulfu?ate\b/i,
      /\be[\s-]?516\b/i,
    ],
    eNumbers: ["E516"],
  },
  {
    canonicalName: "Potassium Aluminum Sulfate",
    category: "other",
    aliases: [
      "potassium aluminum sulfate",
      "potassium aluminium sulphate",
      "potassium alum",
      "e522",
    ],
    severity: "medium",
    matchPatterns: [
      /\bpotassium\s*alumini?um\s*sulfu?ate\b/i,
      /\bpotassium\s*alum\b/i,
      /\be[\s-]?522\b/i,
    ],
    eNumbers: ["E522"],
  },
  {
    canonicalName: "Sodium Phosphate",
    category: "other",
    aliases: [
      "sodium phosphate",
      "trisodium phosphate",
      "disodium phosphate",
      "monosodium phosphate",
      "e339",
    ],
    severity: "medium",
    matchPatterns: [
      /\b(?:tri|di|mono)?sodium\s*phosphate\b/i,
      /\be[\s-]?339\b/i,
    ],
    eNumbers: ["E339"],
  },
  {
    canonicalName: "Sodium Erythorbate",
    category: "other",
    aliases: ["sodium erythorbate", "e316"],
    severity: "low",
    matchPatterns: [/\bsodium\s*erythorbate\b/i, /\be[\s-]?316\b/i],
    eNumbers: ["E316"],
  },
  {
    canonicalName: "Tertiary Butylhydroquinone in Oil",
    category: "other",
    aliases: ["tbhq in oil", "antioxidant tbhq"],
    severity: "high",
    matchPatterns: [/\bantioxidant\s*tbhq\b/i],
  },
  {
    canonicalName: "Polydextrose",
    category: "other",
    aliases: ["polydextrose", "e1200"],
    severity: "low",
    matchPatterns: [/\bpolydextrose\b/i, /\be[\s-]?1200\b/i],
    eNumbers: ["E1200"],
  },
  {
    canonicalName: "Disodium Dihydrogen Pyrophosphate",
    category: "other",
    aliases: [
      "disodium dihydrogen pyrophosphate",
      "sodium acid pyrophosphate",
      "sapp",
      "e450",
    ],
    severity: "low",
    matchPatterns: [
      /\bdisodium\s*dihydrogen\s*pyrophosphate\b/i,
      /\bsodium\s*acid\s*pyrophosphate\b/i,
      /\bsapp\b/i,
      /\be[\s-]?450\b/i,
    ],
    eNumbers: ["E450"],
  },
];
